export const categories = [
    {
        _id: "649a962cbea2ffe7898224af",
        name: "Food & Beverage",
        image: "https://static.moneylover.me/img/icon/ic_category_foodndrink.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224ba",
        name: "Vehicle Maintenance",
        image: "https://static.moneylover.me/img/icon/icon_130.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224b6",
        name: "Television Bill",
        image: "https://static.moneylover.me/img/icon/icon_84.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224b4",
        name: "Electricity Bill",
        image: "https://static.moneylover.me/img/icon/icon_125.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224b8",
        name: "Other Utility Bills",
        image: "https://static.moneylover.me/img/icon/icon_138.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224bd",
        name: "Education",
        image: "https://static.moneylover.me/img/icon/ic_category_education.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224c6",
        name: "Streaming Service",
        image: "https://static.moneylover.me/img/icon/icon_94.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224b2",
        name: "Water Bill",
        image: "https://static.moneylover.me/img/icon/icon_124.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224c8",
        name: "Investment",
        image: "https://static.moneylover.me/img/icon/ic_category_invest.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224c9",
        name: "Pay Interest",
        image: "https://static.moneylover.me/img/icon/icon_4.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224cc",
        name: "Salary",
        image: "https://static.moneylover.me/img/icon/ic_category_salary.png",
        type: true,
    },
    {
        _id: "649a962cbea2ffe7898224ca",
        name: "Outgoing Transfer",
        image: "https://static.moneylover.me/img/icon/icon_142.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224b9",
        name: "Home Maintainance",
        image: "https://static.moneylover.me/img/icon/icon_29.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224cd",
        name: "Other Income",
        image: "https://static.moneylover.me/img/icon/ic_category_other_income.png",
        type: true,
    },
    {
        _id: "649a962cbea2ffe7898224b0",
        name: "Transportation",
        image: "https://static.moneylover.me/img/icon/ic_category_transport.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224b1",
        name: "Rentals",
        image: "https://static.moneylover.me/img/icon/icon_136.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224c1",
        name: "Home Services",
        image: "https://static.moneylover.me/img/icon/icon_8.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224c3",
        name: "Fitness",
        image: "https://static.moneylover.me/img/icon/icon_70.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224c0",
        name: "Pets",
        image: "https://static.moneylover.me/img/icon/icon_53.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224b3",
        name: "Phone Bill",
        image: "https://static.moneylover.me/img/icon/icon_134.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224b5",
        name: "Gas Bill",
        image: "https://static.moneylover.me/img/icon/icon_139.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224bb",
        name: "Medical Check Up",
        image: "https://static.moneylover.me/img/icon/ic_category_doctor.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224be",
        name: "Houseware",
        image: "https://static.moneylover.me/img/icon/icon_107.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224ce",
        name: "Incoming Transfer",
        image: "https://static.moneylover.me/img/icon/icon_143.png",
        type: true,
    },
    {
        _id: "649a962cbea2ffe7898224c2",
        name: "Other Expense",
        image: "https://static.moneylover.me/img/icon/ic_category_other_expense.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224b7",
        name: "Internet Bill",
        image: "https://static.moneylover.me/img/icon/icon_126.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224c7",
        name: "Fun Money",
        image: "https://static.moneylover.me/img/icon/icon_49.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224bc",
        name: "Insurances",
        image: "https://static.moneylover.me/img/icon/icon_137.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224bf",
        name: "Personal Items",
        image: "https://static.moneylover.me/img/icon/icon_41.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224c5",
        name: "Gifts & Donations",
        image: "https://static.moneylover.me/img/icon/ic_category_donations.png",
        type: false,
    },
    {
        _id: "649a962cbea2ffe7898224cb",
        name: "Collect Interest",
        image: "https://static.moneylover.me/img/icon/icon_118.png",
        type: true,
    },
    {
        _id: "649a962cbea2ffe7898224c4",
        name: "Makeup",
        image: "https://static.moneylover.me/img/icon/icon_63.png",
        type: false,
    },
];
